### ISSUE TITLE
Unable to deploy a job

### ISSUE THREAD

**Issue by juandspy** [RedHatInsights/clowder#618]
## Context

I'm trying to deploy a job with `bonfire` and Clowder to an ephemeral cluster. Here is the configuration:
- [clowdapp.yaml](https://github.com/RedHatInsights/insights-results-aggregator-exporter/blob/b2767866f8ad1ae5e05dea78392f162abdb895eb/deploy/clowdapp.yaml)
- `test.yaml`:
```yaml
appsFile:
  host: gitlab
  repo: insights-platform/cicd-common
  path: bonfire_configs/ephemeral_apps.yaml

apps:
- name: ccx-data-pipeline
  components:
    - name: insights-results-aggregator-exporter
      host: github
      repo: RedHatInsights/insights-results-aggregator-exporter
      path: deploy/clowdapp.yaml
      ref: CCXDEV-5895
      parameters:
        CLOWDER_ENABLED: "true"
        IMAGE_TAG: latest
    - name: ccx-insights-results
      host: github
      repo: RedHatInsights/insights-results-aggregator
      path: deploy/clowdapp.yaml
      ref: master
      parameters:
        CLOWDER_ENABLED: "true"
        CLOUDWATCH_ENABLED: "false"
        IMAGE_TAG: qa
```
- commands:
```
ns=$(bonfire namespace reserve)
bonfire deploy -c test.yaml -n $ns ccx-data-pipeline 
```

## Results

Running `oc get jobs -n $ns` returns "No resources found".

## Extra information

If I set a `schedule` it works.

## Questions

- Are jobs supported? Or only cronjobs?
- Is this a problem of `bonfire`?
- Is my `clowdapp.yaml` badly configured?

Thanks in advance.
